print("What's your name:")
name=input("You: ")
print()
print("Hello",name)
print()
birth_year = input("Enter your Birth Year:")
age = 2022 - int(birth_year)
print()
print("Your Age Is:")
print(age)
